### ISSUE TITLE
Blood type is set to Red_Blood for creatures and NPCs regardless of the value

### ISSUE THREAD

**Issue by alvazir** [Greatness7/tes3#3]
I've noticed that blood type is set to red_blood for everything with "blood" on saving. Removing "& 0b111" from following lines possibly fixes the issue:
https://github.com/Greatness7/tes3/blob/a0aa81a382db5179164c3e4b3bc899d0e3cf44f0/libs/esp/src/types/npc.rs#L359
https://github.com/Greatness7/tes3/blob/a0aa81a382db5179164c3e4b3bc899d0e3cf44f0/libs/esp/src/types/creature.rs#L260

    flags | (blood_type & 0b111 << 10)
=>
     flags | (blood_type << 10)

**Comment by Greatness7** [comment]
Should be fixed as of adc2f3b.
